language: python
python:
  - 2.6
  - 2.7
  - 3.3
env: 
  global: 
  - secure: |-
      YZRZzjEVXWcKYWz+L+TI7Odun0ak8ORBHrg4UzrzzX6ok1cZAS4UxAT42DpS
      xknP+sUVNziHpOVDVDnIZ7XG8+NISfBC+mwFmOLfxPiXFqC+/6XZWv4FlHJO
      op5AummUolF8bX7SFOLjG6/Eox9mFOsw8+aIqhly44hlmJ2tpLY=
  - secure: |-
      NzPo81Xb2xuMwcT1JszIPSohGDdJvwim/8zALMSr2ZirL74O3Edsq0DXG6dm
      vy9jcppjKsa8bq9SFrqikVMDUsP/ktW+VoTDbA/JvPBtjFpdDot53T//arsA
      bd494n9a4kQG5gnAnqSRy9QRAXMAs4M3IuccjR0CuebbsXIzLZQ=
  - secure: |-
      Ex+cw8adFNwK7UJ1DQTz0FHprhkohsNJqRwNYrvHmaW9bIZIOAj+14uTHpN1
      u1zteyW91/Lro9JQ32b31TXWlLG0ftl+L8WdOp9+Mx36CbvwKSvxwuTkreg/
      UUdL2mBKMMdt+HCC8rvTnMuZhCkfqtpZIbSGQvIOZlhDdeULZFw=
  - secure: |-
      BAhyQxN6cQv9PQgtSYG2HjuOHbhfX8bePJ7QA5wQpqh5NG2jFviY/AQMAt3t
      l7jd8ZFscac4nygpypX1T3VBd7ZjN94SND17KiLC98SSW8lJPh4Ef/+4/6L3
      /ZSFsZebbr3y5E8Dzm5bzVlOVDC+o2mTDF51ckr+0l4VhAu6vE0=
  - SCREEN_NAME=__twython__
  - PROTECTED_TWITTER_1=TwythonSecure1
  - PROTECTED_TWITTER_2=TwythonSecure2
  - TEST_TWEET_ID=332992304010899457
  - TEST_LIST_ID=574
script: nosetests -v test_twython:TwythonAPITestCase test_twython:TwythonAuthTestCase --cover-package="twython" --with-coverage
install: pip install -r requirements.txt
notifications:
  email: false
